### PR TITLE
vars instead of hardcoded strings and removed duplicate app/console

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by mvhirsch** [comment]
:+1:

**Comment by OskarStark** [comment]
any chance to get this merged?

**Comment by jaugustin** [comment]
@OskarStark could you do your PR against 1.4 branch `master` branch is deprecated.

**Comment by OskarStark** [comment]
@jaugustin done!

Use this PR instead please: https://github.com/propelorm/PropelBundle/pull/333

**Pull request closed without merging**
