### PR TITLE
Resolve deprecated function usages

### LINKED ISSUE #350: Deprecated function usages
There are some deprecated (since SF 2.7) function usages which should be fixed.

Examples:

screenshot 2015-08-05 16 46 02

### PR DESCRIPTION
**Pull request by gharlan**
#350

### CODE REVIEW

**Comment by gharlan** [comment]
This were the easy things.

It's more difficult to resolve these messages:

* The Symfony\Component\Form\Extension\Core\ChoiceList\ObjectChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead.
* The "choice_list" option is deprecated since version 2.7 and will be removed in 3.0. Use "choice_loader" instead.

**Comment by gharlan** [comment]
Maybe this can be merged as-is?
The missing parts could be done in another PR (by someone other or by me when I have more time).

**Comment by gharlan** [comment]
(rebased)

**Comment by havvg** [comment]
Thanks!

**Pull request merged**
