### PR TITLE
Symfony 3 Form generation and new ModelType logic

### PR DESCRIPTION
**Pull request by IceShack**
This PR is based on my other PR: https://github.com/propelorm/PropelBundle/pull/396

This is a very rough draft. I'll add some Unit-Tests and cleanup later.

Form Generation:
It doesn't use the BaseAbstractType anymore (I didn't really understand, why it was needed)
Add some special behaviour for foreignKeys so the TypeGuesser uses the ModelType

ModelType:
I created a new PropelChoiceLoader similar to the Doctrine implementation

And if merged back to the 1.5-Branch would fix this issue: https://github.com/propelorm/PropelBundle/issues/394

### CODE REVIEW

**Comment by marcj** [comment]
Hey @IceShack, what the state of this pr? :)

**Comment by IceShack** [comment]
@marcj As long as somebody has checked the code, it should be fine to merge as well.

**Comment by marcj** [comment]
ping @havvg  :)

**Comment by marcj** [comment]
Merged in branch 3.0

**Pull request closed without merging**
