### PR TITLE
Make PropelBundle available for Symfony 3.X

### PR DESCRIPTION
**Pull request by IceShack**
Updated composer.json dependency
Replaced deprecated dialog helper with question helper

### CODE REVIEW

**Comment by IceShack** [comment]
The question helper was already available in Symfony 2.5 so there should be no compatibility issues with Symfony 2.5 or higher.

**Comment by marcj** [comment]
:+1:

**Comment by IceShack** [comment]
Unfortunately not yet ready, there seems to be some problems with the collector for the profiler...

**Comment by IceShack** [comment]
Am I right to assume that the PropelBundle should work with PHP < 5.4?

**Comment by IceShack** [comment]
Before I forget:
Form generation command works, but generated forms are not compatible with symfony 3.X

Should I create a separate issue for that?

**Comment by gharlan** [comment]
> Am I right to assume that the PropelBundle should work with PHP < 5.4?

you are talking about the 2.x version of the bundle, right?
Propel 2 requires php 5.5, so the bundle can not work with php < 5.5..

**Comment by IceShack** [comment]
> Propel 2 requires php 5.5, so the bundle can not work with php < 5.5

Thanks, I could have checked myself.

**Comment by peter17** [comment]
Class `Propel\Bundle\PropelBundle\Form\ChoiceList\ModelChoiceList` extends `Symfony\Component\Form\Extension\Core\ChoiceList\ObjectChoiceList` which has been removed in favor of `Symfony\Component\Form\ChoiceList\ArrayChoiceList` in Symfony3.

It seems to me that there are a significant number of adjustments to do in PropelBundle to have Propel2 work with Symfony3...

**Comment by havvg** [comment]
Please revert changes in the `composer.json` and rebase the branch on 2.0 so it can be merged :)

**Comment by IceShack** [comment]
Should the form problems be a separate PR?

**Comment by marcj** [comment]
> Should the form problems be a separate PR?

@IceShack which problems? Is this ready to merge? Would like to merge it with https://github.com/propelorm/PropelBundle/pull/403 asap. :+1:

**Comment by IceShack** [comment]
The FormGeneration Stuff is in #403.

This PR should be ready to merge. Haven't checked in a while ;-)

**Comment by marcj** [comment]
Thanks @IceShack!

**Pull request merged**
