### PR TITLE
Read "propel_converter" options from request attributes

### LINKED ISSUE #448: YAML files parsed in production
In my app blackfire.io gives me this recommendation:

screenshot 2017-02-24 18 00 53

The yaml parsings are caused by this line:
https://github.com/propelorm/PropelBundle/blob/3.0/Request/ParamConverter/PropelParamConverter.php#L107

This part was added in #245 (ping @havvg).

I'm not sure, how we could "fix" it.

### PR DESCRIPTION
**Pull request by gharlan**
closes #448

### CODE REVIEW

**Comment by gharlan** [comment]
ping @havvg and @marcj 

On many pages in my app it brings a performance boost of ~40%.

screenshot 2017-03-13 11 08 40

**Comment by gharlan** [comment]
> On many pages

Pages where I'm using implicit ParamConverters like this:

```php
    /**
     * @Route("/foo/{id}", name="foo.view")
     */
    public function fooAction(Request $request, Foo $foo)
    {
    }
```

**Comment by gharlan** [comment]
ping :)

**Comment by gharlan** [comment]
ping ;)

**Comment by marcj** [comment]
Sorry, @havvg is away somehow. Merged, thanks :)

**Pull request merged**
