### PR TITLE
Symfony 4.0 updates

### PR DESCRIPTION
**Pull request by kingchills**
Added support for Symfony 4.0.  Updated unit tests to remove deprecated functions, and match current object serialization strings for YamlDumper

### CODE REVIEW

**Comment by eugenekurasov** [comment]
When this PR will be merge?
I see all tests is passed

**Comment by eugenekurasov** [comment]
Hi @cristianoc72  can you merge this PR?

**Comment by cristianoc72** [comment]
@eugenekurasov sorry, I can't: I haven't push rights on this repo

**Comment by marcj** [comment]
Will this remove Symfony 2.8-3.x support? If so, we need to merge this in a new 4.x branch.

**Comment by kingchills** [comment]
It looks like @cristianoc72 confirmed working in 3.4, and I have confirmed this will break in 2.8.  Shall I update the readme to reflect working versions?  Looks like it would make sense to create it's own branch until I can figure out backwards compatibility

**Comment by marcj** [comment]
Yes, please update the readme accordingly. I changed the target branch to 4.0

**Comment by eugenekurasov** [comment]
@kingchills can you update readme?

**Comment by eugenekurasov** [comment]
@kingchills thank you
Ping @marcj

**Comment by marcj** [comment]
Thanks!

**Pull request merged**
