### PR TITLE
added support for symfony 3.0 and propel 1.7

### PR DESCRIPTION
**Pull request by Gamesh**
issue  #374

### CODE REVIEW

**Comment by Gamesh** [comment]
all tests where sf >=3 and php >=5.5 passed

**Comment by Gamesh** [comment]
@havvg can this be merged, to branch 1.5, or do i need to change something ?

**Comment by havvg** [comment]
I'm currently on this, I will take a detailed look into it and probably merge this. However Travis currently has network issues, builds are taking ages :)

**Comment by havvg** [comment]
I'm closing this one. The 1.5 branch for Symfony 2.8 LTS is now there, no tagged version yet.

I removed the support for Symfony 3.0 on this branch, the 1.6 branch will be created for explicit 3.0 support, where we can safely remove any deprecated usages.

**Comment by Gamesh** [comment]
ok, thanks

**Pull request closed without merging**
