### PR TITLE
Added the Symfony Bridge as an explicit dependency

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Comment by stof** [comment]
This should also be applied to the 1.1 and 1.2 branches as they don't seem abandonned (changes have been done at the same time than the latest commit in 1.4)

**Comment by fabpot** [comment]
As I'm not sure about the merge policy, I prefer to only submit one PR and let the maintainers decide where to merge it and how to propagate the change.

**Comment by havvg** [comment]
Thanks!

**Comment by stof** [comment]
@havvg how would you apply this to older branches too ? Do you need separate PRs ?

**Comment by marcj** [comment]
I guess we don't need for an one line change for each branch a new PR and am able to change it by ourselves.

**Comment by havvg** [comment]
Everything in place.

**Pull request merged**
